name: Test Coveralls

on:
  workflow_run:
      workflows: [Make project]
      types:
        - completed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "./example/coverage/lcov.info"
        base-path: "./example"
