name: Make project

on: ["push", "pull_request"]

jobs:
  make:
    name: Make
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependent commands
      run: sudo apt-get install cc65

    - name: Build
      run: make

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "./example/coverage/lcov.info"
        base-path: "./example"
