name: Make project

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  make:
    name: Make
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependent commands
      run: sudo apt-get install cc65

    - name: Build
      run: make

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "./example/coverage/lcov.info"
        base-path: "./example"

    - name: Make tarball
      run: tar cvf linux.tar 6502_tester LICENSE README.md

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Binary
        path: linux.tar

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: linux.tar
